// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0AfFMM9IEv_QuflPWvjJ8vtQCI8rj_A',
    appId: '1:715490931280:web:b47f74afea9a096171d755',
    messagingSenderId: '715490931280',
    projectId: 'notessync-94cdd',
    authDomain: 'notessync-94cdd.firebaseapp.com',
    storageBucket: 'notessync-94cdd.firebasestorage.app',
    measurementId: 'G-Z74YQ1S065',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlz-_zHb2TS3ASe3pn8xxtD1Ii4Z1tK4',
    appId: '1:715490931280:android:a526858d0a43042971d755',
    messagingSenderId: '715490931280',
    projectId: 'notessync-94cdd',
    storageBucket: 'notessync-94cdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUAQF7wwmNqWo5LCUwn1HhRtxiRltZ4s',
    appId: '1:715490931280:ios:bda57987a00e5c9271d755',
    messagingSenderId: '715490931280',
    projectId: 'notessync-94cdd',
    storageBucket: 'notessync-94cdd.firebasestorage.app',
    iosBundleId: 'com.example.notessync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUAQF7wwmNqWo5LCUwn1HhRtxiRltZ4s',
    appId: '1:715490931280:ios:bda57987a00e5c9271d755',
    messagingSenderId: '715490931280',
    projectId: 'notessync-94cdd',
    storageBucket: 'notessync-94cdd.firebasestorage.app',
    iosBundleId: 'com.example.notessync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN0AfFMM9IEv_QuflPWvjJ8vtQCI8rj_A',
    appId: '1:715490931280:web:17be655e64ef873e71d755',
    messagingSenderId: '715490931280',
    projectId: 'notessync-94cdd',
    authDomain: 'notessync-94cdd.firebaseapp.com',
    storageBucket: 'notessync-94cdd.firebasestorage.app',
    measurementId: 'G-R7XGFN37XD',
  );
}
